"""add name column to users

Revision ID: f6f1e5a1702f
Revises: 1c8ffab6d22a
Create Date: 2025-03-03 16:44:41.649420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f1e5a1702f'
down_revision: Union[str, None] = '1c8ffab6d22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'delivery_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
