version: "3.7"
services:
  db:
    container_name: "db"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    image: postgres:17
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  redis:
    container_name: "redis_db"
    image: redis:7

  webshop:
    image: webshop:latest
    build:
      context: .
    container_name: webshop_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

  celery:
    image: webshop:latest
    build:
      context: .
    container_name: webshop_celery
    command: sh -c "celery --app=app.tasks.celery_app:celery worker -l INFO"
    env_file:
      - .env-non-dev
    depends_on:
      - redis

volumes:
  postgresdata: